"""add_payload_field_to_messages

Revision ID: f9db44130792
Revises: 005
Create Date: 2026-02-25 21:59:43.875537+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f9db44130792'
down_revision: str | None = '005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('payload', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_task_plans_project_id'), 'task_plans', ['project_id'], unique=False)
    op.create_index(op.f('ix_task_plans_user_id'), 'task_plans', ['user_id'], unique=False)
    op.drop_index(op.f('ix_user_agents_user_id_status'), table_name='user_agents')
    op.alter_column('user_projects', 'workspace_path',
               existing_type=sa.VARCHAR(length=500),
               comment="Local path to user's workspace directory",
               existing_nullable=True)
    op.drop_constraint(op.f('uq_user_projects_user_id_name'), 'user_projects', type_='unique')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_user_projects_user_id_name'), 'user_projects', ['user_id', 'name'], postgresql_nulls_not_distinct=False)
    op.alter_column('user_projects', 'workspace_path',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment="Local path to user's workspace directory",
               existing_nullable=True)
    op.create_index(op.f('ix_user_agents_user_id_status'), 'user_agents', ['user_id', 'status'], unique=False)
    op.drop_index(op.f('ix_task_plans_user_id'), table_name='task_plans')
    op.drop_index(op.f('ix_task_plans_project_id'), table_name='task_plans')
    op.drop_column('messages', 'payload')
    # ### end Alembic commands ###
